### ISSUE TITLE
There is no Rewrapper flag for authentication settings. But Authentication Type required

### ISSUE THREAD

**Issue by raphael10-collab** [bazelbuild/reclient#10]
With this configuration file :
    
    root@k8s-eu-1-master:~/chromium-original/chromium/src/buildtools/reclient/bb-deployments/bare# cat reclientConfigBBFrontend.txt 
    service=127.0.0.1:8980
    instance=$RE_SERVER_INSTANCE
    log_dir=/tmp
    output_dir=/tmp
    proxy_log_dir=/tmp
    depsscanner_address=$scandeps_server_location #distributed with Reclient

I get this error : `Unable to authenticate with RBE service needs to be specified, authentication type (identity) used="unknown authentication type` :
    
    root@k8s-eu-1-master:~/chromium-original/chromium/src/buildtools/reclient/bb-deployments/bare# ../../rewrapper -cfg=reclientConfigBBFrontend.txt -platform=OSFamily=linux,ISA=x86-64,docker=//gcr.io/cloud-marketplace/google/rbe-ubuntu16-04@sha256:b4dad0bfc4951d619229ab15343a311f2415a16ef83bcaa55b44f4e2bf1cf635 -exec_strategy="remote_local_fallback" -dial_timeout="10m" -exec_root="/root/chromium-original/chromium/src" -- /root/tmp/bb-cache/
    F1010 12:59:21.831161  377524 main.go:175] Command failed: rpc error: code = Unauthenticated desc = Unable to authenticate with RBE
    service needs to be specified, authentication type (identity) used="unknown authentication type"

But in `Rewrapper` flags there is no flag for authentication settings : https://github.com/bazelbuild/reclient/blob/main/docs/cmd-line-flags.md#rewrapper

How to make it work ?

**Comment by gkousik** [comment]
I'm guessing the credentials helper proposal we mentioned in https://github.com/bazelbuild/reclient/issues/11 would help with custom auth in this scenario too, so I'm closing this out and keeping the other one open until we actually implement the interface documented there.
