### ISSUE TITLE
Can you please give an example of credental_file, for a self-hosted buildbarn remote instance to work?

### ISSUE THREAD

**Issue by raphael10-collab** [bazelbuild/reclient#11]
As described here: https://github.com/bazelbuild/reclient/issues/10

in Rewrapper flags there is no flag for authentication settings : https://github.com/bazelbuild/reclient/blob/main/docs/cmd-line-flags.md#rewrapper but I get this error : `Unable to authenticate with RBE service needs to be specified, authentication type (identity) used="unknown authentication type`

Since according to https://github.com/bazelbuild/reclient/blob/main/docs/cmd-line-flags.md#notes-on-credentials-and-authentication-source one of these flags :
    

1. credential_file,
2. use_application_default_credentials,
3. use_gce_credentials

is mandatory,

can you please give an example of credental_file, for a self-hosted buildbarn remote instance to work?

**Comment by raphael10-collab** [comment]
Thank you @gkousik . Looking forward for it

**Comment by gkousik** [comment]
I've opened up a discussion here https://github.com/bazelbuild/reclient/discussions/16 with the proposal
