### ISSUE TITLE
Local fallback strips all environment if `env_var_allowlist` is set

### ISSUE THREAD

**Issue by goodov** [bazelbuild/reclient#13]
If you run `reclient` with `env_var_allowlist` variable set, then a local launch (`exec_strategy=local`) or a local fallback (`exec_strategy=remote_local_fallback`) is executed with **only** variables that are listed in `env_var_allowlist`. Is this intended or a bug? Remote execution on [1] **adds** listed variables into the existing non-empty remote environment.

This pretty much breaks local execution in some scenarios, because all important variables, such as `PATH` are cleared when a local fallback is executed. I don't want to add `PATH` into `env_var_allowlist`, because in most cases `PATH` will vary from machine to machine.

The place where the environment is fully replaced:
https://github.com/bazelbuild/reclient/blob/c39ce54bf324d959ea5d6531519182821547d081/internal/pkg/subprocess/subprocess.go#L116-L118

I'd assume this code should append/merge variables into existing environment, instead of replacing it.

1. `docker://gcr.io/chops-public-images-prod/rbe/siso-chromium/linux@sha256:26de99218a1a8b527d4840490bcbf1690ee0b55c84316300b60776e6b3a03fe1`

**Comment by gkousik** [comment]
This behavior is intentional. The goal is that the local execution environment is as close to the remote-execution environment (for example when the action is running inside a docker image on an RBE bot).
And as you said, environment differs from machine to machine, which means if we allow all of the local environment during action execution, actions may not be hermetic. So being intentional about what environment you pass to the action is the intention behind filter the env variables even for local execution (and generally, fewer env vars you have, the more chances the action is hermetic).

**Comment by goodov** [comment]
> This behavior is intentional. The goal is that the local execution environment is as close to the remote-execution environment (for example when the action is running inside a docker image on an RBE bot).

I understand the intention, but I believe the implementation is currently incorrect. What you're saying also means `reclient` should **clear** environment if `cmd.InputSpec.EnvironmentVariables == nil`. Why it's not doing this right now?

> And as you said, environment differs from machine to machine, which means if we allow all of the local environment during action execution, actions may not be hermetic.

This is exactly what's happening in local runs currently if you don't set `env_var_allowlist`. How is that "hermetic"?

**Comment by gkousik** [comment]
> I understand the intention, but I believe the implementation is currently incorrect. What you're saying also means reclient should clear environment if cmd.InputSpec.EnvironmentVariables == nil. Why it's not doing this right now?

If there is no explicitly list of env variables specified to an action, it could either be thought of as either "allow everything" or "allow nothing" and we are currently doing "allow everything". I agree that it'll result in a more hermetic action but I'll have to check with existing internal integrations to make sure it doesn't break any of them (and if it does, work with those users to ensure they are migrated). I'll take this as a feature request.

**Comment by goodov** [comment]
> If there is no explicitly list of env variables specified to an action, it could either be thought of as either "allow everything" or "allow nothing" and we are currently doing "allow everything". I agree that it'll result in a more hermetic action but I'll have to check with existing internal integrations to make sure it doesn't break any of them (and if it does, work with those users to ensure they are migrated). I'll take this as a feature request.

Please just don't make it worse. The point of this issue is to allow the full envrionment in local runs even if `env_var_allowlist` is set. Doing the opposite does break things, I can tell that because I've experienced this myself when I was setting up Chromium builds from Mac/Linux/Windows host OSes.

Such critical things as `PATH` should always exist in the environment, but everything breaks apart when you just want to add an environment variable into the remote execution. In this case you're forced to add ALL required variables (including PATH) for local fallbacks to work. In reality this doesn't make sense, because you don't want to enforce `PATH` remotely.

There's also one pretty crazy logic in `reclient`: if you set `toolchain_inputs`, then `reclient` will enforce `PATH` as if I set `env_var_allowlist=PATH` manually. In this case local fallbacks will be executed with only `PATH` env var set.

**Comment by gkousik** [comment]
Hi, sorry for the late response and thanks for clarifying the scenario. I discussed this usecase internally too and we came to the conclusion that allowing all env variables do make sense. Our reasoning was this:

1. The environment variables set during remote-execution is actually an implementation detail of each remote-execution backend. While the spec allows for passing in the environment variables, the RBE backend could very well append some default variables like `PATH` during remote-execution. So it would be hard for reclient to match the same variables as the remote-execution backend.
2. Given the local-execution anyway doesn't match the variables from the remote-execution backend, we may as well be closer to what local execution would have looked like without reclient (in which case all the env variables in the process environment would be available to the process).

I've sent an internal change to allowlist the full environment for local execution (hoping its merged in the next few days and available here).

> There's also one pretty crazy logic in reclient: if you set toolchain_inputs, then reclient will enforce PATH as if I set env_var_allowlist=PATH manually. In this case local fallbacks will be executed with only PATH env var set.

Could you please file a separate issue for this?

**Comment by gkousik** [comment]
Fixed in https://github.com/bazelbuild/reclient/commit/bc65d589e4c5ce62c7a188de7e5fbfb708b1e70c.
