### ISSUE TITLE
How to get scandeps_server 

### ISSUE THREAD

**Issue by Ruoye-W** [bazelbuild/reclient#25]
I build reclient with command "bazelisk build --config=clangscandeps //cmd/..." in Linux, but there is no scandeps_server in bazel-bin/cmd/scandeps. Could you please let me know if there are any missing dependencies in my build?

**Comment by gkousik** [comment]
You can build scandeps_server with one of the following commands:

```
# Build scandeps_server with clangscandeps for C++ include scanning
bazelisk build --config=clangscandeps-service //cmd/scandeps:scandeps_server
```

OR

```
# Build scandeps_server with goma libs for C++ include scanning
bazelisk build --config=remotelinux --config=goma-service //cmd/scandeps:scandeps_server
```
