### ISSUE TITLE
Is there an equivalent to bazels `--remote_header`

### ISSUE THREAD

**Issue by MarshallOfSound** [bazelbuild/reclient#3]
Looking at using an RBE cluster that you authenticate to via a custom header `x-foo-bar=my-key`, it's not super clear how auth currently works in reclient but it doesn't look like there is an equivalent for this bazel flag.

Could someone either tell me I'm wrong 😆 or point me in the right direction of the code I could implement this in? Auth feels quite splayed, I see references to external tokens but not sure how that's wired in

**Comment by Yannic** [comment]
IIUC, you can use `--credential_file` to specify a path to a JSON file with credentials to provide arbitrary headers.

We are also working on improving authentication for `reclient` similar to what Bazel supports :)

**Comment by MarshallOfSound** [comment]
@Yannic It looks like `credential_file` expects some kind of JWT for GCP 🤔 

```
couldn't create RPC creds for https://www.googleapis.com/auth/cloud-platform: couldn't create RPC creds from creds: google: read JWT from JSON credentials: 'type' field is "" (expected "service_account"), authentication type (identity) used="credentials file"
```

I don't see a non-GCP based auth option rn, even scanned the code a bit, the external token flag doesn't appear to be wired up

**Comment by gkousik** [comment]
I think this issue and the discussion we are having in https://github.com/bazelbuild/remote-apis-sdks/pull/507 are related. I'll update here when we flush out an interface for how the credentials helper is going to look like.

**Comment by banikharbanda** [comment]
Closing this out since it's being tracked in #11
