### ISSUE TITLE
Local racing runs miss local environment variables

### ISSUE THREAD

**Issue by goodov** [bazelbuild/reclient#31]
https://github.com/bazelbuild/reclient/commit/bc65d589e4c5ce62c7a188de7e5fbfb708b1e70c now keeps local variables for local runs, but local racing runs still miss the local environment.

This code is missing `a.cmd` manipulations:
https://github.com/bazelbuild/reclient/blob/bc65d589e4c5ce62c7a188de7e5fbfb708b1e70c/internal/pkg/reproxy/action.go#L460-L464

that were added here:
https://github.com/bazelbuild/reclient/blob/bc65d589e4c5ce62c7a188de7e5fbfb708b1e70c/internal/pkg/reproxy/action.go#L104-L115

related https://github.com/bazelbuild/reclient/issues/13
cc @gkousik

**Comment by goodov** [comment]
cc @gkousik any chance this can be fixed in a near future? This breaks `racing` strategy in when an environment variable must exist.

**Comment by gkousik** [comment]
Apologies for the delay - will take a look at this today.

**Comment by gkousik** [comment]
I've sent an internal fix - I expect it to be merged next week after review.
