### ISSUE TITLE
Any timeline/plan to update Bazel version 6.4.0 or 7.0?

### ISSUE THREAD

**Issue by jwxw** [bazelbuild/reclient#33]
Hi Reclient contributors,

Currently looking into integrating Bazel buildfarm. Their most recent update switched Bazel version from **v6.4.0 to v7.0.2**, and Reclient currently just added support to Bazel **6.3.2**. Is there any plan to upgrade to Bazel v7.0 in the near future? Love to leverage v7.0 if possible. 

Reference:
- Bazel Buildfarm upgrade to Bazel v7.0.2: https://github.com/bazelbuild/bazel-buildfarm/commit/b38568b7a5e5c9421f9ed89257cf5f0bd29881a2

**Comment by gkousik** [comment]
We are currently in the process of updating to Bazel 7.1.1. I'll close the issue for now.
