### ISSUE TITLE
[auth] experimental_credential_helper command can only run once

### ISSUE THREAD

**Issue by kfarnung** [bazelbuild/reclient#40]
I've been experimenting with the `experimental_credential_helper` for our deployment and I noticed that `reproxy` can only execute the helper once per process launch. This means that if the credentials expire twice during a single process lifetime (possible with short-lived access tokens), authentication completely fails until the process is restarted.

The root cause is that the [`NewExternalCredentials`](https://github.com/bazelbuild/reclient/blob/ae445f05221cbe0846903985b72c4b69900ad3cd/internal/pkg/auth/auth.go#L440C2-L440C65) function creates the `exec.Cmd` object and passes it along to the `Credential`. Unfortunately, once it's executed once, it cannot be executed again:

https://pkg.go.dev/os/exec#Cmd

> Cmd represents an external command being prepared or run.
>
> A Cmd cannot be reused after calling its Run, Output or CombinedOutput methods.

The fix is to collect the path and arguments separately, then create the `exec.Cmd` right before execution and discard it immediately after. I added a new test and modified the code to support it, are you open to contributions yet?

My change: https://github.com/bazelbuild/reclient/commit/8eca8f0ab0df10076563fe10d6ac7834a867927e

**Comment by bentekkie** [comment]
Thanks for the bug report, this should be fixed as of d6858f2

**Comment by kfarnung** [comment]
Thanks for the quick turnaround, was this already a known issue?

**Comment by bentekkie** [comment]
We were root causing a similar issue already which turned out to be the same issue. Thanks for the pointer on exec.Cmd

**Comment by kfarnung** [comment]
@bentekkie I haven't seen a new version get published to CIPD yet, do you know when the next version is expected?

**Comment by bentekkie** [comment]
We post new versions after each release bump. It's a long weekend here in Canada so most likely sometime later next week
