### ISSUE TITLE
fail_early_min_action_count should be ignored when using exec_strategy local

### ISSUE THREAD

**Issue by YngveNPettersen** [bazelbuild/reclient#43]
I have been setting up a reclient cluster, to replace our Goma cluster.

I've been doing basic testing of a minimal, no-remote-workers, cache-only buildfarm server.

Unfortunately, the local-only builds kept failing after less than 10K builditems, with the error "this build has encountered too many local fallbacks".

I eventually found that the problem was that fail_early_min_action_count was set to 4000 from integrating recommendations from https://github.com/EngFlow/reclient-configs .

Setting that and the associated value to 0 solved the issue.

However, I think that, when exec_strategy for the reclient is local (remote cache-only) this setting should be ignored, since all build actions are intended to be local.

**Comment by MikeS-rec** [comment]
It is possible to get local fallbacks, even with LERC.  If the call to runLERC results in a not ok status, it will run the action locally and increment the numFallbacks count.  In the runs where you were having the failure, did you have any warning messages like this?

'LERC failed with x, falling back to local.'

**Comment by YngveNPettersen** [comment]
I can't recall having seen any of those; OTOH, I was mostly looking at the end of the build log (of 8000-100000+ build items).

The build was a cache seed operation (the mode was local), so all builds steps would be executed locally, and not retrieving anything cached from the remote cache.

**Comment by MikeS-rec** [comment]
I'll leave this issue open, if you happen to encounter the situation again add some logs here and we can take a look.

**Comment by YngveNPettersen** [comment]
Should be fairly simple to reproduce: Set the execute policy to "local", set the field's value to 4000, use an empty cache server (buildfarm in my case), Start building Chromium from scratch. Should fail in about 10000 steps (of 80000+).

**Comment by YngveNPettersen** [comment]
It turned out that I was using a very old version reclient (due to one version used by Chromium breaking the system, and never updated until this week).

A new build with the current version does not reproduce the issue
