### ISSUE TITLE
building phase : ERROR: 'docker' was requested for mnemonic CcNinjaMakeRule but no strategy with that identifier was registered. Valid values are: [processwrapper-sandbox, standalone, remote, worker, sandboxed, local, linux-sandbox]

### ISSUE THREAD

**Issue by raphael10-collab** [bazelbuild/reclient#5]
During the `building phase` with `bazelisk` I'm getting this error:

    raphy@raohy:~/chromium-original/chromium/src/reclient$ bazelisk build --config=clangscandeps //cmd/...
    INFO: Build options --//:include_scanner, --cxxopt, and --host_cxxopt have changed, discarding analysis cache.
    INFO: Analyzed 27 targets (0 packages loaded, 20251 targets configured).
    INFO: Found 27 targets...
    ERROR: 'docker' was requested for mnemonic CcNinjaMakeRule but no strategy with that identifier was registered. Valid values are: [processwrapper-sandbox, standalone, remote, worker, sandboxed, local, linux-sandbox]
    INFO: Elapsed time: 1.516s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully

    raphy@raohy:~/chromium-original/chromium/src/reclient$ bazelisk --version
    bazel 5.3.0

O.S: Ubuntu 22.04

How to make it work ?

**Comment by bentekkie** [comment]
This should be fixed now with https://github.com/bazelbuild/reclient/commit/52f072b2505372a9ffe099fefe078bfdc289b107

**Comment by raphael10-collab** [comment]
It's ok now : https://drive.google.com/file/d/1F9hCznHiBW3SFc0rW1vbGB33U52SwIR0/view?usp=sharing

Thank you!!
