### ISSUE TITLE
External Contribution Status

### ISSUE THREAD

**Issue by daniel-sudz** [bazelbuild/reclient#51]
I have been stalled on getting this repo to build on windows and mac for a while and I want to know how to resolve this moving forward. There have been some fixes merged here and there but I would ideally want to be able to contribute PRs directly to have a faster turnaround. 
@bentekkie

**Comment by gkousik** [comment]
Hi,
Thanks for raising this - I'm working on setting up a workflow so that we can import Github PRs. Will update on this in a week.

**Comment by daniel-sudz** [comment]
> Hi, Thanks for raising this - I'm working on setting up a workflow so that we can import Github PRs. Will update on this in a week.

Thanks for the consideration. Would it be possible to also consider one of the following: 

- Add a public build integration in this repo (ie. github actions) 
- Or publish the actual existing build steps that are used to build the repo

It's really hard to report or even communicate any issue when it's not particularly clear what the problem is. Ie. the most recent commit ff3bec62931ef02bf6b4c9f07c2437fdcbd686f0 prevents me from resolving "@io_bazel_rules_go" and I can't tell if this is a local setup issue or something else. 

Thanks again!

**Comment by gkousik** [comment]
Hi thanks again for the followup, we are working on setting up a public build integration through Github Actions (expect an update on that too in ~a week).

**Comment by daniel-sudz** [comment]
thank you so much to everyone that resolved this :smile:

**Comment by gkousik** [comment]
Sorry, there's one final component here (its to update the CONTRIBUTING.md file). I'm waiting on some approvals to do that, I'll keep this open until then.

**Comment by daniel-sudz** [comment]
> Sorry, there's one final component here (its to update the CONTRIBUTING.md file). I'm waiting on some approvals to do that, I'll keep this open until then.

thanks, when that gets added I have a first trial run for you: https://github.com/bazelbuild/reclient/pull/60 :smiley:

**Comment by gkousik** [comment]
The wheels have turned and I've updated the CONTRIBUTING.md page. Closing this one.
