### ISSUE TITLE
BOM-utf8 formatted files with #include in the first line not being scanned correctly by Goma input scanner

### ISSUE THREAD

**Issue by lainswork** [bazelbuild/reclient#64]
**Issue Title:** BOM-utf8 formatted files with #include in the first line not being scanned correctly by Goma input scanner

**Issue Description:**

When using the Goma input scanner, if our files are in BOM-utf8 format and have an `#include` statement in the first line, the header file declared by this `#include` statement does not appear in the scan results.

**Comment by gkousik** [comment]
Interesting issue! However we aren't actively developing on the Goma include scanner (we are passively exploring alternatives in that space). The code for the Goma include scanner now lives here - https://chromium.googlesource.com/infra/goma-input-processor/.

Its unlikely we'll get to fixing it, but would be happy to accept patches to the above mentioned repo.

**Comment by mostynb** [comment]
@gkousik: I have a few prereq fixes that need a +1 before I look into this, I wonder if you could take a look?
* https://chromium-review.googlesource.com/c/infra/goma-input-processor/+/5791307
* https://chromium-review.googlesource.com/c/infra/goma-input-processor/+/5791309
* https://chromium-review.googlesource.com/c/infra/goma-input-processor/+/5791308
