### ISSUE TITLE
platform field on remote-apis v2 action not implemented

### ISSUE THREAD

**Issue by daniel-sudz** [bazelbuild/reclient#75]
In remote-apis there was a change to move platform from command to action: 

```go
  // The platform requirements for the execution environment. The server MAY
  // choose to execute the action on any worker satisfying the requirements, so
  // the client SHOULD ensure that running the action on any such worker will
  // have the same result.  A detailed lexicon for this can be found in the
  // accompanying platform.md.
  // DEPRECATED as of v2.2: platform properties are now specified directly in
  // the action. See documentation note in the
  // [Action][build.bazel.remote.execution.v2.Action] for migration.
  Platform platform = 5 [ deprecated = true ];
```

I'm looking at  the action class in https://github.com/bazelbuild/reclient/blob/55282d59f1e4d5ff6b043bea4e9807c0e31dfd15/internal/pkg/reproxy/action.go#L52 and it does not appear to have carried over this change. 

I have not taken a deeper look but in our production workloads I am seeing the `action.Platform` field coming back as null.

**Comment by daniel-sudz** [comment]
paging @gkousik for triage

**Comment by gkousik** [comment]
We actually seem to be setting the platform property on the action as well if its supported (this code is in remote-apis-sdks though) - https://github.com/bazelbuild/remote-apis-sdks/blob/master/go/pkg/rexec/rexec.go#L192.

Does your server advertise an API version of >= 2.2? (https://github.com/bazelbuild/remote-apis-sdks/blob/master/go/pkg/client/capabilities.go#L114) If so, you shouldn't run into this issue. Let me know if you find any othger bug in the reclient side of things!
