### ISSUE TITLE
why LERC actions add a platformVersionKey attribute, since the build is hermatic

### ISSUE THREAD

**Issue by danni-yan** [bazelbuild/reclient#86]
I have deployed a remote build cluster. For CI, I use the `remote_local_fallback` mode to speed up the build. For developers, I want to provide only remote cache ability(LERC). However, I found that the `local` mode adds platformVersionKey attribute to diff the two actions. Repo only has a simple comment mentioning that bugs may be encountered.

```
		// For LERC actions, there's a chance we may have reclient bugs.
		// We want to ensure we don't persist those across actions.
		// We also want to add version if the option to do so is set to true.
```
Can you explain specifically what errors might occur?

https://github.com/bazelbuild/reclient/blob/981e9fd32786718254a56b78ee8f2c26de1ff378/internal/pkg/reproxy/server.go#L438

**Comment by i-box** [comment]
anyone here?
@gkousik  hello, can you explain this?

**Comment by mrahs** [comment]
Hi Daniel.

The comment indicates that it's easier to take the hit of executing locally over the burden of having to clean the cache from bad entries, in case there was a bug in reclient that caused created the bad entries.

**Comment by danni-yan** [comment]
So, this is a precautionary measure. If client only fetches the remote cache without updating it, there should be no impact, right?

**Comment by danni-yan** [comment]
according to this issue, I cannot use local strategy and not update the cache
https://github.com/bazelbuild/reclient/issues/87

**Comment by mrahs** [comment]
>So, this is a precautionary measure. If client only fetches the remote cache without updating it, there should be no impact, right?

The effect of this logic is that cached results from clients that were running LERC can only be used by clients using the same strategy and reclient version.

**Comment by danni-yan** [comment]
Got it. tks
